#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
DEVFILE="$SCRIPT_DIR/../../src/necos.ts"
PRODFILE="$SCRIPT_DIR/../../build/src/necos.js"

# check global ts node installation
TS_NODE_INSTALLED=$(npm list ts-node)

if [[ "${FLAGS[*]}" =~ "--dev" ]] || [[ "${FLAGS[*]}" =~ "--ci" ]]; then
  if [[ "$TS_NODE_INSTALLED" == *empty* ]]; then
    echo "ts-node is not installed. Please install ts-node to run NECos."
    return
  fi

  npx ts-node-esm "$DEVFILE" -- $FLAGS
else
  if [ ! -e "$PRODFILE" ]; then
    echo "NECos build not found in project root! Did you run ./necos build?"
  else
    export NODE_ENV=production

    node "$PRODFILE" -- $FLAGS
  fi
fi